laeongmulti/MoneyTrack

package-lock.json
package.json
src/components/Expense/Expense.vue
src/components/Expense/ExpenseCalender.vue
src/components/Expense/ExpenseFilterContainer.vue
src/components/Expense/ExpenseFilterItem.vue
src/components/Expense/FilterPanel.vue
src/css/expense/expense.css

Expense 페이지에 대한 컴포넌트 생성 및 expense 페이지에 연결하였습니다.
feat: add ExpenseCalendar Component
feat: add filterContainer Component
feat: add filter component module
feat: ExpenseCalender, FilterPanel 등 추가 및 Expense.vue 연결
chore: install vue3-datepicker for date selection

feat: create and connect Expense page components

---

src/css/common/common.css

MoneyTrack 프로젝트의 디자인 시스템 구축을 위해 공통 스타일을 정의하였습니다.  
색상, 텍스트, 버튼 등 자주 사용하는 요소들을 클래스로 분리하여 재사용성을 높이고 유지보수를 용이하게 했습니다.
- 공통 색상 변수 도입 및 적용 (`--trk-green`, `--trk-ivory` 등)
- 배경색, 텍스트색, 테두리색 유틸리티 클래스 (`.trk-bg-*`, `.trk-text-*`, `.trk-br-*`)
- 공통 버튼 스타일 정의
- `.trk-btn-confirm`: 확인 버튼 (초록색)
- `.trk-btn-cancel`: 취소 버튼 (회색)
- 그림자 및 라운딩 처리, hover 효과 포함
- `src/css/common.css`
- 다른 페이지에 공통 스타일 점진적으로 적용

style: 공통 UI 스타일 정의 (색상, 텍스트, 버튼)

---

src/components/Expense/AddModal.vue
src/components/Expense/Expense.vue
src/components/Expense/ExpenseCalender.vue
src/components/Expense/ExpenseFilterContainer.vue
src/components/Expense/ExpenseFilterItem.vue
src/components/Expense/FilterPanel.vue
src/stores/category.js
src/stores/expense.js

지출 내역 추가 기능을 구현하였습니다.
카테고리 목록을 DB에서 동적으로 불러오도록 수정하였으며, 수입/지출 판별 로직의 오류를 수정했습니다.

Feature add expense v2

---

src/App.vue
src/components/common/Alert.vue
src/components/providers/AlertProvider.vue

- Alert.vue: 사용자 정의 알림 UI 컴포넌트 구현 (타입별 스타일, 아이콘, 트랜지션 포함)
- AlertProvider.vue: provide/inject 기반 전역 알림 시스템 구축
- App.vue: AlertProvider로 전체 앱을 감싸 전역 상태 전달 구조 구성
- 각 페이지에서 inject('useAlert')로 알림 호출 가능
- success: 초록 체크 아이콘
- error: 빨간 느낌표 아이콘
- warning: 노란 삼각형 아이콘
- info: 파란 정보 아이콘
```js
const alert = inject('useAlert')
alert.success('성공 메시지입니다!')

feat: 사용자 정의 알림(Alert) 컴포넌트 연결 및 전역 알림 시스템 구현

---

package-lock.json
package.json
src/components/Expense/ExpenseCalender.vue

- 캘린더 날짜 선택을  vue-datepicker-next 형식으로 변경

Refactor replace datepicker

---

src/components/Expense/AddModal.vue
src/components/Expense/Expense.vue
src/stores/expense.js

유저 아이디에 따라 expense add 및 fetch를 진행하도록 변경

Update use userid

---

src/components/Header/Header.vue
src/stores/usetStore.js

- `Header.vue` 구현
- 로고, 메뉴 버튼, 로그인/로그아웃 버튼 포함
- PC/모바일 반응형 레이아웃 대응
- 로그인 상태에 따른 UI 분기
- 로그인 시: 홈, 달력, 통계 메뉴 + 로그아웃 버튼
- 비로그인 시: 로그인 버튼
- 로그아웃 시 `Alert` 컴포넌트 연동
- 전역 useAlert API를 통해 '로그아웃 되었습니다.' 알림 표시
- 로그인 성공 시 알림(`Alert`)은 추후 `Login.vue`에서 처리 예정
- 로그인 상태는 `pinia`의 `userStore`에서 관리

feat: Header 컴포넌트 구현 및 로그인 상태 분기/알림 연동

---

src/components/Expense/AddModal.vue
src/components/Expense/Expense.vue
src/components/Expense/ExpenseFilterContainer.vue
src/stores/expense.js

**내역 추가 컴포넌트 수정**
- 내역 추가 시 선택한 날짜로 모달이 생성되도록 변경
- 카테고리 초기값 선택 오류 수정
- 임시 로그인 코드 제거
- 내역 추가 성공 여부에 따라 alert component를 이용하여 모달이 뜨도록 변경

Feature expense add feedback modal

---

src/components/Expense/AddModal.vue
src/components/Expense/CategoryButton.vue
src/components/Expense/CategoryOption.vue
src/components/Expense/ExpenseCalender.vue
src/components/Expense/ExpenseFilterContainer.vue
src/components/Expense/ExpenseFilterItem.vue
src/components/Expense/FilterPanel.vue
src/css/expense/expense.css

** Expense 관련 페이지 **
- 컴포넌트 분리
- categoryButton, categoryOption 등
- css 위치 지역 변수가 되도록 변경

Refactor expense

---

src/components/Expense/CategoryButton.vue
src/components/Expense/FilterPanel.vue
src/components/Statistics/Statistics.vue
src/components/Statistics/StatisticsGraph.vue

**카테고리 버튼 컴포넌트 적용**
- 필터에서와 같은 형태의 버튼 사용으로 통일성 증대
**적용된 모습**

style: 공통된 카테고리 버튼 적용을 위한 디자인 변경

---

src/components/Expense/ExpenseFilterContainer.vue
src/components/Expense/FilterPanel.vue
src/components/Statistics/Statistics.vue
src/components/Statistics/StatisticsFilterBox.vue
src/components/Statistics/StatisticsGraph.vue
src/css/expense/expense.css

**Statistic Style 수정**
- 실제 desktop 화면
- 실제 모바일 화면
**Expense Style 수정**
- 모바일에서 깨지지 않도록 수정

style: Update statistics&expense style

---

src/components/ExpenseDetail/ExpenseDetail.vue
src/components/ExpenseDetail/ExpenseEdit.vue
src/css/expenseDetail/expenseDetail.css
src/css/expenseDetail/expenseEdit.css

style 수정 및 오류 수정

---

src/components/Expense/AddModal.vue
src/components/Expense/ExpenseCalenderCell.vue
src/components/Expense/ExpenseFilterContainer.vue
src/components/Expense/ExpenseFilterItem.vue

**feat: expense 페이지 금액의 경우 , 사용하도록 변경**
- ex: 1,000처럼 표기되도록 변경

feat: expense 페이지 금액의 경우 , 사용하도록 변경

---

src/components/Expense/ExpenseCalenderCell.vue
src/components/Expense/ExpenseFilterContainer.vue

feat: Expense 제거된 목록 나타나지 않도록 변경
- 제거된 항목을 캘린더와 목록에서 제거

feat: Expense 제거된 목록 나타나지 않도록 변경

---

src/components/Expense/FilterPanel.vue
src/components/Statistics/StatisticsFilterBox.vue
src/components/Statistics/StatisticsGraph.vue

style: style 깨짐 현상 수정

---

src/components/Home/Home.vue

FIX: home 에서 hover 이펙트 세분화

---

src/components/common/BackButton.vue

📌 변경 내용
- BackButton 컴포넌트에 to props 추가
- 기본 동작은 router.back()
- to props가 주어지면 해당 경로로 router.push(to)
- 페이지마다 유연하게 뒤로가기 버튼 사용 가능하도록 개선
❔ 사용 예시
- `<BackButton />` 쓰면 router.back()이 기본
- `<BackButton to="/home" />` 처럼 쓰면 해당 페이지로 이동

feat: BackButton 컴포넌트 커스텀 경로 이동 기능 추가

---

src/components/Expense/CategoryButton.vue
src/components/Statistics/StatisticsGraph.vue
src/css/expense/expense.module.css
src/css/expense/expenseCalenderCell.module.css

**Expense 페이지**
- expense 페이지 하단에 margin 추가하여 하단 nav에 걸리지 않도록 함
- expense 페이지 container 배경 제거
**Category Button**
- active시 bg-color 변경

Detail style

---

src/components/Expense/CategoryButton.vue
src/components/Expense/ExpenseCalender.vue
src/components/Expense/ExpenseFilterContainer.vue
src/css/expense/expenseCalenderCell.module.css
src/css/expense/expenseFilterItem.module.css

**Expense 페이지**
- calendat에서 hover시 배경 색 변화 추가
- `+ button` hover시 배경 색 변화 추가
- category button hover시 반응 추가

css: hover에 따른 반응 추가

---

src/css/header/header.css

🔧 변경 사항
- 헤더 타이틀(.header__title)과 버튼들의 font-size를 상향 조정해 가독성 향상
- 모바일 하단 네비게이션(.header__mobile-nav) 위치를 더 아래로 이동해 버튼과의 간격 확보

style: 헤더 글씨 크기 조정 및 모바일 메뉴 위치 개선

---

src/components/Home/MyExpense.vue
src/components/Statistics/CategoryList.vue

FIX: Home 단순 수정

---

src/components/Home/Home.vue

FIX: Home 테마 수정
